# Beritahu SonarCloud di mana lokasi kod sumber
sonar.sources=.

# KRITIKAL: Hanya scan fail ini sahaja (Kod tulisan anda)
sonar.inclusions=cli.py, main.py, sdet/**

# KRITIKAL: JANGAN scan folder sampah/library ini
sonar.exclusions=**/.venv/**, **/venv/**, **/__pycache__/**, **/*.html, **/*.mp4, **/*.iso, **/*.bin