name: SDET Cross-Platform Build

# Skrip ini akan berjalan apabila anda 'push' ke branch main, 
# atau apabila anda meletakkan tag versi (contoh: v1.0.0)
on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' 

permissions:
  contents: write # Dibenarkan untuk mencipta file di bahagian Release

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    # Buka 3 OS serentak (Windows, Ubuntu Linux, macOS)
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    # ---------------------------------------------------------
    # KUNCI KESELAMATAN (SHA PINNING): 
    # Menggunakan SHA hash untuk mengelak Serangan Rantaian Bekalan
    # ---------------------------------------------------------
    - name: Checkout Code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up Python 3.11
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter pyinstaller

    - name: Build CLI (PyInstaller)
      run: >
        pyinstaller --clean --onefile --console 
        --name SDET-CLI-${{ runner.os }} 
        cli.py

    - name: Build GUI (PyInstaller)
      run: >
        pyinstaller --clean --onefile --windowed --collect-all customtkinter 
        --name SDET-GUI-${{ runner.os }} 
        main.py

    - name: Zip macOS App Bundle (macOS Only)
      if: runner.os == 'macOS'
      run: |
        cd dist
        zip -r SDET-GUI-macOS.zip SDET-GUI-macOS.app
        rm -rf SDET-GUI-macOS.app

    - name: Upload Artifacts
      uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.3
      with:
        name: SDET-Binaries-${{ runner.os }}
        path: dist/*

    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.0.8
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*